### PR TITLE
Addl bulk cards2

### PR DESCRIPTION
**Pull request by joshayers**
This isn't really ready to merge, but I wanted to get your opinion on a few things before continuing.

I updated `rdcards` to recursively follow include statements.  There is a function input to disable it if desired, but it currently defaults to True.  Should I add a `follow_includes` parameter to the functions that use `rdcards` in case the user wants to ignore includes?

I added two new functions - `wtcard8` and `wtcard16`.  They take a list of fields, and format them as 8 or 16 character fixed field cards.  All the formatting, line wraps, and continuations are handled automatically.  I also added functions to write some additional cards that use them.  For each of them, I picked an 8 or 16 field size, but it feels kind of arbitrary.  What do you think about adding an input to allow the user to pick one or the other?  It can be optional with a sensible default for each card type.

Some of the existing cards have some complex formatting and could be simplified with these new functions - `wtrbe3` stands out for example.  Any objections to making changes to some of them?

### CODE REVIEW

**Comment by twmacro** [comment]
@joshayers, I **love** these additions!! :-)

I've only taken a quick look so far, and noticed just one thing I'd update: in _check_for_symbols, there is a bare "except". So, I'm thinking this:

        except:
            msg = f"Symbol found in INCLUDE, but it is not defined: {symbol:}"

should be:

        except KeyError:
            msg = f"Symbol found in INCLUDE, but it is not defined: {symbol:}"

Also, does that ':' in the format do anything?

I ran through the tests and saw that some tests in test_n2p.py are failing because I don't have '/loads/nx_dmaps/v9/nas2cam_103.v9' on my home computer:

    FAILED tests/test_n2p.py::test_formrbe3_1 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_2 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_3 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_4 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_UM_1 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_UM_2 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_UM_3 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_UM_4 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_UM_5 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'
    FAILED tests/test_n2p.py::test_formrbe3_UM_6 - FileNotFoundError: [Errno 2] No such file or directory: '/loads/nx_dmaps/v9/nas2cam_103.v9'

That'll be easy to fix, but it makes me think about the default setting for `follow_includes`. (I think True is the best so far.)

> Should I add a follow_includes parameter to the functions that use rdcards in case the user wants to ignore includes?

Yes, I think that would be great!

> I added two new functions - wtcard8 and wtcard16. They take a list of fields, and format them as 8 or 16 character fixed field cards. All the formatting, line wraps, and continuations are handled automatically. I also added functions to write some additional cards that use them. For each of them, I picked an 8 or 16 field size, but it feels kind of arbitrary. What do you think about adding an input to allow the user to pick one or the other? It can be optional with a sensible default for each card type.

Great functions!! I like the idea of an option. If that's too much work, I'm also agreeable to using something sensible like some routines do now. Probably 16 default when there are floating point numbers and 8 when that works.

> Some of the existing cards have some complex formatting and could be simplified with these new functions - wtrbe3 stands out for example. Any objections to making changes to some of them?

Go for it! That would be fantastic! :-) 

I have a question for you. I had another thought while I was scrolling through the code: I think `rdcards` should be updated to add the `*` to the definition line, as in:

    def rdcards(
        f,
        name,
        *,
        blank=None,
        return_var="array",
        ...

I bet most code wouldn't be impacted, and I feel there are just too many parameters to not require most of them to be named. What do you think?

Many, many thanks for your contributions!!

Best regards,
Tim

**Comment by joshayers** [comment]
Thanks for the review, Tim. I’m on vacation this week but I’ll get into this when I get back.

**Comment by twmacro** [comment]
Awesome! Have a blast!

**Comment by joshayers** [comment]
> I've only taken a quick look so far, and noticed just one thing I'd update: in _check_for_symbols, there is a bare "except". So, I'm thinking this:
> 
> ```
>     except:
>         msg = f"Symbol found in INCLUDE, but it is not defined: {symbol:}"
> ```
> 
> should be:
> 
> ```
>     except KeyError:
>         msg = f"Symbol found in INCLUDE, but it is not defined: {symbol:}"
> ```
> 
> Also, does that ':' in the format do anything?

Good catch - I'll add the error type to the except block.

On the ':', I actually thought that was required to use a variable in a format string. It's not needed for anything else.


> I have a question for you. I had another thought while I was scrolling through the code: I think `rdcards` should be updated to add the `*` to the definition line, as in:
> 
> ```
> def rdcards(
>     f,
>     name,
>     *,
>     blank=None,
>     return_var="array",
>     ...
> ```
> 
> I bet most code wouldn't be impacted, and I feel there are just too many parameters to not require most of them to be named. What do you think?

Yeah, I agree that would make sense.

**Review by twmacro — APPROVED** [review]
This is fantastic! :-)

**Comment by twmacro** [comment]
Hi @joshayers,

Are you ready for me to merge this in?

One thing I'm pondering: would it be worthwhile to update wtcard8 (and wtcard16 maybe?) to figure out that ``1.234567`` is better than `` 1.23+00``? What do you think? Such an update is certainly not needed for this merge to take place; I'm just looking ahead.

Many, many thanks! :-)
Tim

**Comment by joshayers** [comment]
I wanted to give it one more look before merging.

> One thing I'm pondering: would it be worthwhile to update wtcard8 (and wtcard16 maybe?) to figure out that `1.234567` is better than ` 1.23+00`? What do you think? Such an update is certainly not needed for this merge to take place; I'm just looking ahead.

I was going to ask you about this.  There are a couple of functions in pyNastran that do this - 
[field_writer_8.print_float_8](https://github.com/SteveDoyle2/pyNastran/blob/main/pyNastran/bdf/field_writer_8.py) and [field_writer_16.print_float_16](https://github.com/SteveDoyle2/pyNastran/blob/main/pyNastran/bdf/field_writer_16.py).  They probably need some tweaks, but what do you think about copying the general approach?  It seems complicated, but they do maximize readability when possible and accuracy when required.

**Comment by twmacro** [comment]
Cool! Let me know when I can merge it in.

I took a quick look at the pyNastran links. That's actually what I was picturing (and had used a similar approach in some old C code), but I wondered if there might be a more clever way in Python. I'd be perfectly happy that approach though. And of course, I'm not requesting that you update your code for this ... somebody could do it later. :-)

**Review by twmacro — APPROVED** [review]

**Comment by joshayers** [comment]
I think I'm done with this branch.  Need to get some other work done :)  Let me know if you see any issues, otherwise I think it's good to go.

**Pull request merged**
