### PR TITLE
Fix test warnings

### PR DESCRIPTION
**Pull request by joshayers**
I fixed a number of warnings that were output from the tests.

There were two types of changes to the actual code

1. Assigning `a[0] = b` where `b` is an array with shape (1, ).  This is deprecated in NumPy 1.25 and will be an error in the future.  I replaced it with `a[0] = b[0]`.
2. The `numpy.find_common_types` function is also deprecated in NumPy 1.25.  I replaced it with `numpy.result_type`.  I think this meets the intent.

The other changes just catch warnings so they are verified and aren't displayed when running the tests.  I made one change per commit so you can review them easily.

### CODE REVIEW

**Comment by twmacro** [comment]
Hi @joshayers,

I appreciate your help on this greatly! :-) Cleaning the tests up has been on my TODO list for a long time. Everything looks great except I got 2 fails when running the updated tests on my Linux machine (maybe different matplotlib versions ?). The first one is this one:

        def test_era():
            M, K, D, freq_hz, zeta, phi = get_model_data()
        
            dt = 0.01
            t = np.arange(0, 1, dt)
            F = np.zeros((3, len(t)))
            ts = ode.SolveExp2(M, D, K, dt)
            sol = ts.tsolve(force=F, v0=[1, 1, 1])
        
            with pytest.warns(UserWarning) as records:
                era_fit = era.ERA(
                    sol.v,
                    sr=1 / dt,
                    auto=True,
                    input_labels=["x", "y", "z"],
                    all_lower_limits=0.1,
                    FFT=True,
                    # FFT_range=(0.0, 25.0),
                    # show_plot=False,
                    verbose=False,
                )
    >           verify_one_match(records, [r"Matplotlib.*using agg", r"figure layout.*tight"])
    
    pyyeti/tests/test_era.py:66: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    records = WarningsChecker(record=True), regexes = ['Matplotlib.*using agg', 'figure layout.*tight']
    
        def verify_one_match(records, regexes):
            """Verify that at least one warning matches each regex."""
            for regex in regexes:
                match_found = False
                for record in records:
                    match_found = (
                        re.search(regex, record.message.args[0]) is not None or match_found
                    )
    >           assert match_found, f"No matching warning found: {regex}"
    E           AssertionError: No matching warning found: figure layout.*tight
    E           assert False
    
    pyyeti/tests/test_era.py:42: AssertionError

And the second one is:

        def test_wtrspline_rings():
            theta1 = np.arange(0, 359, 360 / 5) * np.pi / 180
            rad1 = 50.0
            sta1 = 0.0
            n1 = len(theta1)
            ring1 = np.vstack(
                (
                    np.arange(1, n1 + 1),  # ID
                    sta1 * np.ones(n1),  # x
                    rad1 * np.cos(theta1),  # y
                    rad1 * np.sin(theta1),
                )
            ).T  # z
            theta2 = np.arange(10, 359, 360 / 7) * np.pi / 180
            rad2 = 45.0
            sta2 = 1.0
            n2 = len(theta2)
            ring2 = np.vstack(
                (
                    np.arange(1, n2 + 1) + 100,  # ID
                    sta2 * np.ones(n2),  # x
                    rad2 * np.cos(theta2),  # y
                    rad2 * np.sin(theta2),
                )
            ).T  # z
        
            uset1 = (
                "Name 1",
                n2p.addgrid(None, ring1[:, 0].astype(int), "b", 0, ring1[:, 1:], 0),
            )
            uset2 = (
                "Name 2",
                n2p.addgrid(None, ring2[:, 0].astype(int), "b", 0, ring2[:, 1:], 0),
            )
        
            fig = plt.figure("rspline demo", figsize=(8, 6))
            fig.clf()
            ax = fig.add_subplot(1, 1, 1, projection="3d")
        
            with StringIO() as f:
                nastran.wtrspline_rings(
                    f, ring1, ring2, 1001, 2001, makeplot=ax, independent="ring1"
                )
                u, c = nastran.bulk2uset(f)
                rsplines1 = nastran.rdcards(f, "RSPLINE")
        
            with StringIO() as f:
    >           with pytest.warns(UserWarning, match=r"figure layout.*changed.*tight"):
    E           Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) were emitted.
    E           The list of emitted warnings is: [].

What do you think?
Regards,
Tim

**Comment by joshayers** [comment]
I'm using maplotlib 3.7.2.

That doesn't seem like a very meaningful warning.  It's probably fine to just swallow it using `warnings.catch_warnings`.  What do you think?

**Comment by twmacro** [comment]
I was thinking the same thing! :-)

**Comment by joshayers** [comment]
I think I fixed those two errors.  Let me know if it still doesn't pass for you.

**Review by twmacro — APPROVED** [review]

**Comment by twmacro** [comment]
Thanks @joshayers! :-)

**Pull request merged**
